"""empty message

Revision ID: c94b06ec7e4d
Revises: 8edc146dd040
Create Date: 2018-07-28 12:26:21.784429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c94b06ec7e4d'
down_revision = '8edc146dd040'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('F_guess', sa.PickleType(), nullable=True))
    op.add_column('post', sa.Column('QF_guess', sa.PickleType(), nullable=True))
    op.add_column('post', sa.Column('R16_guess', sa.PickleType(), nullable=True))
    op.add_column('post', sa.Column('SF_guess', sa.PickleType(), nullable=True))
    op.add_column('post', sa.Column('group_stage_guess', sa.PickleType(), nullable=True))
    op.add_column('tournament', sa.Column('F_game', sa.PickleType(), nullable=True))
    op.add_column('tournament', sa.Column('F_teams', sa.PickleType(), nullable=True))
    op.add_column('tournament', sa.Column('QF_games', sa.PickleType(), nullable=True))
    op.add_column('tournament', sa.Column('QF_teams', sa.PickleType(), nullable=True))
    op.add_column('tournament', sa.Column('R16_games', sa.PickleType(), nullable=True))
    op.add_column('tournament', sa.Column('R16_teams', sa.PickleType(), nullable=True))
    op.add_column('tournament', sa.Column('SF_games', sa.PickleType(), nullable=True))
    op.add_column('tournament', sa.Column('SF_teams', sa.PickleType(), nullable=True))
    op.add_column('tournament', sa.Column('group_stage_games', sa.PickleType(), nullable=True))
    op.add_column('tournament', sa.Column('group_stage_teams', sa.PickleType(), nullable=True))
    op.drop_column('tournament', 'games')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament', sa.Column('games', sa.BLOB(), nullable=True))
    op.drop_column('tournament', 'group_stage_teams')
    op.drop_column('tournament', 'group_stage_games')
    op.drop_column('tournament', 'SF_teams')
    op.drop_column('tournament', 'SF_games')
    op.drop_column('tournament', 'R16_teams')
    op.drop_column('tournament', 'R16_games')
    op.drop_column('tournament', 'QF_teams')
    op.drop_column('tournament', 'QF_games')
    op.drop_column('tournament', 'F_teams')
    op.drop_column('tournament', 'F_game')
    op.drop_column('post', 'group_stage_guess')
    op.drop_column('post', 'SF_guess')
    op.drop_column('post', 'R16_guess')
    op.drop_column('post', 'QF_guess')
    op.drop_column('post', 'F_guess')
    # ### end Alembic commands ###
